app:
  port: 8080

db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: 'root'
    database: 'kapok'
    port: 3306
    charser: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true

redis:
  host: 'localhost'
  port: 6379
  db: 0
  prifix: 'nest'

jwt:
  secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
  expiresin: '2h'
